<?php

/**
 * @file
 * Install, uninstall, schema and update hooks for Language Icons.
 */

/**
 * Implements hook_install().
 */
function languageicons_install() {
  // Use our supplied set of icons by default.
  $path = drupal_get_path('module', 'languageicons') . DIRECTORY_SEPARATOR . 'flags' . DIRECTORY_SEPARATOR . '*.png';
  \Drupal::configFactory()
    ->getEditable('languageicons.settings')
    ->set('path', $path)
    ->save();
}